import type { Metadata } from "next";
import "./globals.scss";
import { notoSans } from "./fonts";
import { Footer, Header, Sidebar } from "@/layout";

export const metadata: Metadata = {
  title: {
    template: "%s | Nextjs app",
    default: "MyTop - tourses top"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${notoSans.className}`}>
        <div className="layout md:layout-main grid grid-rows-main grid-cols-mobile md:grid-cols-main min-h-screen">
          <Header className="header block md:hidden" />
          <Sidebar className="sidebar hidden md:block" />
          <div className="site-content">
            {children}
          </div>
          <Footer className="footer" />
        </div>
      </body>
    </html>
  );
};