import type { Metadata } from "next";
import "./globals.scss";
import { notoSans } from "./fonts";

export const metadata: Metadata = {
  title: {
    template: "%s | Nextjs app",
    default: "MyTop - tourses top"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${notoSans.className}`}>{children}</body>
    </html>
  );
}